name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12741e7bc4f128e569aac64396373e8313c033400fb5bc01533605face59b830"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
