name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "445ee2942ece8db6a4e562d76699edce8da1f1129aa704d884f894cc5cebf429"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
