name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8455ef93b7723d9d74289b64a9bd25f15f8d34a9ab36f3559df8f043083338d"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
