name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90295cc7cc34cc852b3d355a015c8052c5940d2033279b97314e27a66b85f346"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
