name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86e31ddf1da66ab76b7e0e4d3983859f37dcc5d8f1c54b9d93202118450ca808"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
