name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2263e2faebff72768562b551268e6de064e0a31b0b5c277b2118338c39e53b73"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
