name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e18bf64630596d180e5c553b6c7931e7df38a9f0b7a89ec0435537cfff66e3dd"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
