name = "jitterpack"
author = "Jitter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5f29ba71856ab595376f0a676f8c737f7a1da1eb4a86e0ec787ca3a8523dda9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
